version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lekhai-postgres
    environment:
      POSTGRES_DB: lekhai_dev
      POSTGRES_USER: lekhai_user
      POSTGRES_PASSWORD: lekhai_dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lekhai_user -d lekhai_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local